-- MySQL Script generated by MySQL Workbench
-- Fri May 21 17:41:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblio` DEFAULT CHARACTER SET utf8 ;
USE `biblio` ;

-- -----------------------------------------------------
-- Table `biblio`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblio`.`persona` (
  `persona_id` INT(10) NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `apellido` VARCHAR(25) NOT NULL,
  `alias` VARCHAR(10) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`persona_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblio`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblio`.`categoria` (
  `categoria_id` INT(10) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblio`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblio`.`libro` (
  `libro_id` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `persona_id` INT(10) NOT NULL,
  `categoria_id` INT(10) NOT NULL,
  PRIMARY KEY (`libro_id`),
  INDEX `fk_libro_categoria_idx` (`categoria_id` ASC),
  INDEX `fk_libro_persona1_idx` (`persona_id` ASC),
  CONSTRAINT `fk_libro_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `biblio`.`categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `biblio`.`persona` (`persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
